# Generated by Django 4.0.2 on 2022-02-01 15:57

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('played_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
