# Generated by Django 4.0.2 on 2022-02-12 11:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('statify_api', '0002_alter_song_artist_alter_song_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=1000)),
                ('display_name', models.CharField(max_length=1000)),
                ('spotify_account', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
